config/routes.rb
Rails.application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'
  root 'static_pages#start'
  get '/homedark',  to: 'static_pages#home'
  get '/homelight', to:'static_pages#home-light'
  get '/login',           to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  get '/contact',         to: 'messages#new', as: 'new_message'
  post '/contact',        to: 'messages#create', as: 'create_message'
  get '/error',           to: 'messages#error_page'
  get '/success',         to: 'messages#success_page'
  get '/portfolio',       to: 'static_pages#portfolio'
  resources :users
  resources :posts
  resources :categories
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_aboutslide-light.html.erb
<div class="slide" id="slide2-light" data-anchor="slide2-light"> 
		
		<div class="row align-items-center">
			<div class="col-md-2">
			
			<div class="section-left">
				<div class="bottom-block">
					<div class="logo-sides center hidden">
						<a href="#firstPage/slide1-light">Home</a>
					</div>
				</div>
			</div>
			
			</div>
			
    		<div class="col-md-8">
   				<div class="center hidden">
					<h1 class="center light"><u>About</u></h1>
						<div class="about-block zoom">
						<h4 class="center"><u>Full Service Custom Website & Web App Development</u></h4>
						<p class="about-text-padding">
								As a full service web developer, making your wbesite perfect from inception launch is what matters most.
								I have two years experience in custom web development, digital marketing, & SEO, and offer the following services:
								
									<li><strong>Full service website development</strong></li>
									<li><strong>SEO Optimization & Digital Marketing Consulting</strong></li>
									<li><strong>Front-end webiste redesign</strong></li>
								
						</p>
					</div>
		    	</div>
    		</div>
    		
    		<div class="col-md-2">
    			
    		<div class="section-right">
    			<div class="bottom-block">
					<div class="logo-sides center hidden">
						<a href="#firstPage/slide3-light">Pricing</a>
					</div>
				</div>
			</div>
			
    		</div>
    		
		</div>
		
			<div class="bottom">
				<div class="center hidden">
					<div class="bottom-block">
						<div class="logo-sides">	
							<a href="#secondPage">Contact</a>
						</div>
					</div>
				</div>
			</div>
</div>

app/views/static_pages/_aboutslide.html+phone.erb
<div class="slide fp-auto-height-responsive" id="slide1" data-anchor="slide2"> 

		<div class="row align-items-center">
			
   				<div class="center hidden">
					<h5><u>About</u></h5>
		    	</div>
    	</div>
    		
    		
				<div class="center hidden padding-mobile-bottom">
						<div class="about-block zoomx2">
						<h4 class="center"><u>Full Service Custom Website & Web App Development</u></h4>
						<p class="about-text-padding">
								As a full service web developer, making your wbesite perfect from inception launch is what matters most.
								I have two years experience in custom web development, digital marketing, & SEO, and offer the following services:
								
									<li><strong>Full service website development</strong></li>
									<li><strong>SEO Optimization & Digital Marketing Consulting</strong></li>
									<li><strong>Front-end webiste redesign</strong></li>
								
						</p>
					</div>
		    	</div>
				
					
	
    		
		<div class="row hidden">
					
			<div class="col-sm-3 col-md-offset-1-and-half">	
				<div class="logo-sides-mobile center hidden">
					<a href="#firstPage/slide1">Home</a>
					&nbsp;
					<%= image_tag('arrow-left.png') %>
				</div>
			</div>
						
			<div class="col-sm-3">
				<div class="logo-sides-mobile center hidden">
					<a href="#secondPage">Contact</a>
					&nbsp;
					<%= image_tag('arrow-down.png') %>
				</div>
			</div>
						
			<div class="col-sm-3">
				<div class="logo-sides-mobile center hidden">
					<a href="#firstPage/slide3">Pricing</a>
					&nbsp;
					<%= image_tag('arrow-right.png') %>
				</div>
			</div>
						
		</div>	

</div>

app/views/static_pages/_aboutslide.html.erb
<div class="slide" id="slide2" data-anchor="slide2"> 
		
		<div class="row align-items-center">
			<div class="col-md-2">
			
			<div class="section-left">
				<div class="bottom-block">
					<div class="logo-sides center hidden">
						<a href="#firstPage/slide1">Home</a>
					</div>
				</div>
			</div>
			
			</div>
			
    		<div class="col-md-8">
   				<div class="center hidden">
						<h1 class="center"><u>About</u></h1>
						<div class="about-block zoom">
							<h4 class="center"><u>Full Service Custom Website & Web App Development</u></h4>
							<p class="about-text-padding">
								As a full service web developer, making your wbesite perfect from inception launch is what matters most.
								I have two years experience in custom web development, digital marketing, & SEO, and offer the following services:
								
									<li><strong>Full service website development</strong></li>
									<li><strong>SEO Optimization & Digital Marketing Consulting</strong></li>
									<li><strong>Front-end webiste redesign</strong></li>
								
							</p>
						</div>
		    	</div>
    		</div>
    		
    		<div class="col-md-2">
    			
    		<div class="section-right">
    			<div class="bottom-block">
					<div class="logo-sides center hidden">
						<a href="#firstPage/slide3">Pricing</a>
					</div>
				</div>
			</div>
			
    		</div>
    		
		</div>
		
			<div class="bottom">
				<div class="center hidden">
					<div class="bottom-block">
						<div class="logo-sides">	
							<a href="#secondPage">Contact</a>
						</div>
					</div>
				</div>
			</div>
</div>

app/views/static_pages/_contactslide-light.html.erb
<div class="slide" id="slide1-light" data-anchor="slide1-light"> 
		<h1 class="center">Contact</h1>
		&nbsp;
		<%= render 'messages/new' %>
</div>

app/views/static_pages/_contactslide.html.erb
<div class="slide" id="slide1" data-anchor="slide1"> 
		<h1 class="center">Contact</h1>
		&nbsp;
		<%= render 'messages/new' %>
</div>

app/views/static_pages/_homeslide-light.html+phone.erb
<div class="slide" id="section1-light" data-anchor="slide1-light"> 
		
		
		<div class="row align-items-center">
			
   				<div class="center hidden">
					<h5 class="light-text">Christian O'Rourke</h5>
					<h5 class="light-text">Custom Web Development</h5>
					
					
					<div><%= image_tag('swipe.png') %></div>
					<div class="logo-small-mobile center light-text">
						(Swipe for navigation, Tap text boxes to zoom)
					</div>
					<div>
						<button id="dark_button" class="btn-primary btn-lg"><%= link_to "dark", homedark_url %></button>
					</div>
					
		    	</div>
    	</div>
		
		
	<div class="row">
					
			<div class="col-sm-3 col-md-offset-1-and-half">	
				<div class="logo-sides-mobile center hidden">
					<a href="#firstPage/slide3-light">Pricing</a>
					&nbsp;
					<%= image_tag('arrow-left.png') %>
				</div>
			</div>
						
			<div class="col-sm-3">
				<div class="logo-sides-mobile center hidden">
					<a href="#secondPage">Contact</a>
					&nbsp;
					<%= image_tag('arrow-down.png') %>
				</div>
			</div>
						
			<div class="col-sm-3">
				<div class="logo-sides-mobile center hidden">
					<a href="#firstPage/slide2-light">About</a>
					&nbsp;
					<%= image_tag('arrow-right.png') %>
				</div>
			</div>
						
		</div>	
			
</div>

app/views/static_pages/_homeslide-light.html.erb
<div class="slide" id="section1-light" data-anchor="slide1-light"> 
		
		<div class="row align-items-center">
			<div class="col-md-2">
			
			<div class="section-left">
				<div class="logo-sides center hidden">
					<a href="#firstPage/slide3-light" class="light-text">Pricing</a>
				</div>
			</div>
			
			</div>
			
    		<div class="col-md-8">
   				<div class="center hidden">
					<h1 class="light-text">Christian O'Rourke</h1>
					<h1 class="light-text">Custom Web Development</h1>
					<div><%= image_tag('arrow-keys.png') %></div>
					<div>
						<button id="dark_button" class="btn-primary"><%= link_to "dark", homedark_url %></button>
					</div>
					<div class="logo-small center light-text">
						(Use your arrow keys for navigation)
					</div>
		    	</div>
    		</div>
    		
    		<div class="col-md-2">
    			
    		<div class="section-right">
				<div class="logo-sides center hidden">
					<a href="#firstPage/slide2-light" class="light-text">About</a>
				</div>
			</div>
			
    		</div>
    		
		</div>
		
		
		<div class="bottom">
			<div class="center hidden">
				<div class="bottom-block">
					<div class="logo-sides">	
						<a href="#secondPage" class="light-text">Contact</a>
					</div>
				</div>
			</div>
		</div>
			
</div>

app/views/static_pages/_homeslide.html+phone.erb
<div class="slide fp-auto-height-responsive" id="section1" data-anchor="slide1"> 

		<div class="row align-items-center">
			
   				<div class="center hidden">
					<h5>Christian O'Rourke</h5>
					<h5>Custom Web Development</h5>
					
					
					<div><%= image_tag('swipe.png') %></div>
					<div class="logo-small-mobile center">
						(Swipe for navigation, Tap text boxes to zoom)
					</div>
					<div>
						<button id="light_button" class="btn-primary btn-lg"><%= link_to "light", homelight_url %></button>
					</div>
		    	</div>
    	</div>
    		
		<div class="row">
					
			<div class="col-sm-3 col-md-offset-1-and-half">	
				<div class="logo-sides-mobile center hidden">
					<a href="#firstPage/slide3">Pricing</a>
					&nbsp;
					<%= image_tag('arrow-left.png') %>
				</div>
			</div>
						
			<div class="col-sm-3">
				<div class="logo-sides-mobile center hidden">
					<a href="#secondPage">Contact</a>
					&nbsp;
					<%= image_tag('arrow-down.png') %>
				</div>
			</div>
						
			<div class="col-sm-3">
				<div class="logo-sides-mobile center hidden">
					<a href="#firstPage/slide2">About</a>
					&nbsp;
					<%= image_tag('arrow-right.png') %>
				</div>
			</div>
						
		</div>	

</div>

app/views/static_pages/_pricingslide-light.html+phone.erb
<div class="slide fp-auto-height-responsive" id="slide3-light" data-anchor="slide3-light"> 

		<div class="row align-items-center">
			
   				<div class="center hidden">
					<h5><u>Pricing</u></h5>
		    	</div>
    	</div>
    		
    		

  			

				
					<div class="pricing-box-mobile zoom">
								
								<h4 class="center mobile-text-xlg"><u>Landing Pages</u></h4>
								<ul>
									<li>
										<p class="mobile-text-lg">Custom Landing Page/Mobile Page</p>
									</li>
									<li>
										<p class="mobile-text-lg">SEO Optimization</p>
									</li>
									<li>
										<p class="mobile-text-lg">Basic Social Media Integration</p>
									</li>
								</ul>
								<h4 class="center mobile-text-xlg">Base rate: $300/page</h4></p>
							
						</div>
				
						<div class="padding-box"></div>
				
						<div class="pricing-box-mobile zoom">
									
								<h4 class="center mobile-text-xlg"><u>Multi-Page Websites</u></h4>
								<ul>
									<li>
										<p class="mobile-text-lg">Custom Landing Page/Mobile Pages</p>
									</li>
									<li>
										<p class="mobile-text-lg">SEO Optimization</p>
									</li>
									<li>
										<p class="mobile-text-lg">Custom Social Media Integration</p>
									</li>
								</ul>
								<h4 class="center mobile-text-xlg">Base rate: $300 + $100/page</h4>

						</div>
						
						<div class="padding-box"></div>
				
						<div class="pricing-box-mobile zoom">
								
								<h4 class="center mobile-text-xlg"><u>Multi-Page Blog Websites</u></h4>
								<ul>
									<li>
										<p class="mobile-text-lg">Custom Landing Page/Mobile Pages</p>
									</li>
									<li>
										<p class="mobile-text-lg">Custom Blog & CMS Integration</p>
									</li>
									<li>
										<p class="mobile-text-lg">Custom Social Media Integration</p>
									</li>
									<li>
										<p class="mobile-text-lg">SEO Optimization</p>
									</li>
								</ul>
								<h4 class="center mobile-text-xlg">Base rate: $1200 + $100/page</h4>
								
						</div>
	

    		
    		
		<div class="row">
					
			<div class="col-sm-3 col-md-offset-1-and-half">	
				<div class="logo-sides-mobile center hidden">
					<a href="#firstPage/slide2-light">About</a>
					&nbsp;
					<%= image_tag('arrow-left.png') %>
				</div>
			</div>
						
			<div class="col-sm-3">
				<div class="logo-sides-mobile center hidden">
					<a href="#secondPage">Contact</a>
					&nbsp;
					<%= image_tag('arrow-down.png') %>
				</div>
			</div>
						
			<div class="col-sm-3">
				<div class="logo-sides-mobile center hidden">
					<a href="#firstPage/slide1-light">Home</a>
					&nbsp;
					<%= image_tag('arrow-right.png') %>
				</div>
			</div>
						
		</div>	

</div>

app/views/static_pages/home-light.html.erb
<% provide(:title, "Light") %>

<div id="fullpage" class="fp-auto-height-responsive">
	
	<div class="preloader"><span class="preloader-gif"></span></div>
	
	<div class="section" data-anchor="firstPage">
		
		<%= render 'homeslide-light' %>
		
		<%= render 'aboutslide-light' %>
		
		<%= render 'pricingslide-light' %>
		
	</div>
	
	<div class="section" id="slide1" data-anchor="secondPage">
		
		<%= render 'contactslide-light' %>
	
	</div>
	
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Dark") %>

<div id="fullpage" class="fp-auto-height-responsive">
	
	<div class="preloader"><span class="preloader-gif"></span></div>
		
	<div class="section" data-anchor="firstPage">
	
		<%= render 'homeslide' %>
		
		<%= render 'aboutslide' %>
		
		<%= render 'pricingslide' %>
	</div>
	
	<div class="section" id="slide1" data-anchor="secondPage">
		
		<%= render 'contactslide' %>
	
	</div>

</div>
	
	

app/views/static_pages/portfolio.html+phone.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
	<%= render 'shared/preloader' %>
	
	<h1 class="glitch center" data-text="Portfolio">Portfolio</h1>
	&nbsp;
	<div class="center side-padding">
	    <p class="portfolio-logo">Full Service Web Development:</p>
	    
	    <div class="row">
	    	<div class="col-md-2"></div>
	    	
	        <div class="col-md-4">
	            <a href="https://www.moonhalf.com/">
	                <%= image_tag('MoonHalf.png', class: 'portfolio-box') %>
	                <p class="portfolio-text">Moonhalf.com</p>
	            </a>
	        </div>
	        
	        <div class="col-md-4">
	            <a href="https://www.countmingya.com/">
	                <%= image_tag('CountMingya.png', class: 'portfolio-box') %>
	                <p class="portfolio-text">CountMingya.com</p>
	            </a>
	        </div>
	        
	        <div class="col-md-2"></div>
	    </div>   
	       
	    <div class="row">
	    	<div class="col-md-2"></div>
	    	
	        <div class="col-md-4">
	            <a href="http://www.emmacate8.com/">
	                <%= image_tag('EmmaCate8.png', class: 'portfolio-box') %>
	                <p class="portfolio-text">EmmaCate8.com</p>
	            </a>
	        </div>
	        
	        <div class="col-md-4">
	        	<a href="https://www.skylinejourney.com/">
	                 <%= image_tag('SkylineJourney.png', class: 'portfolio-box') %>
	                 <p class="portfolio-text portfolio-padding">SkylineJourney.com</p>
	             </a>
	        </div>
	        
	        <div class="col-md-2"></div>
	    </div>
	    
	    <div class="row">
	        	<div class="col-md-4"></div>
	        	
	        	<div class="col-md-4">
	        		<a href="https://www.memeilluminati.com/">
	                 	<%= image_tag('memeilluminati.png', class: 'portfolio-box preset-file6') %>
	                 	<p class="portfolio-text portfolio-padding">MemeIlluminati.com</p>
	             	</a>
	        	</div>
	        	
	        	<div class="col-md-4"></div>
	        </div>
	        
	    <p class="portfolio-logo">Front-end Redesign:</p>
	    	<a href="https://www.tellus360.com/">
	        	<%= image_tag('Tellus360.png', class: 'portfolio-box') %>
	        	<p class="portfolio-text portfolio-padding">Tellus360.com</p>
	    	</a>
	    
	    <p class="portfolio-logo">Git/Ongoing Projects:</p>
	    <a href="https://bitbucket.org/corourke24/"><p class="portfolio-text portfolio-padding">Bit Bucket</p></a>
	    
	    <a href="/"><h1 class="glitch" data-text="Home">Home</h1></a>
	</div>
</meta>

app/views/static_pages/portfolio.html.erb
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;">
	<%= render 'shared/preloader' %>
	
	<h1 class="glitch center" data-text="Portfolio">Portfolio</h1>
	&nbsp;
	<div class="center side-padding">
	    <p class="portfolio-logo">Full Service Web Development:</p>
	    
	    <div class="row">
	    	<div class="col-md-2"></div>
	    	
	        <div class="col-md-4">
	        	<div class="gifs-rows1">
	            
	            <a href="https://www.moonhalf.com/">
	                <%= image_tag('MoonHalf.png', class: 'portfolio-box preset-file') %>
	                <%= image_tag('moonhalf.gif', class: 'portfolio-box gif-file') %>
	                <p class="portfolio-text">Moonhalf.com</p>
	            </a>
	            
	            </div>
	        </div>
	        
	        <div class="col-md-4">
	        	<div class="gifs-rows2">
	        		
	            <a href="https://www.countmingya.com/">
	                <%= image_tag('CountMingya.png', class: 'portfolio-box preset-file2') %>
	                <%= image_tag('countmingya.gif', class: 'portfolio-box gif-file2') %>
	                <p class="portfolio-text">CountMingya.com</p>
	            </a>
	            
	            </div>
	        </div>
	        
	        <div class="col-md-2"></div>
	    </div>   
	       
	    <div class="row">
	    	<div class="col-md-2"></div>
	    	
	        <div class="col-md-4">
	        	<div class="gifs-rows3">
	        		
	            <a href="http://www.emmacate8.com/">
	                <%= image_tag('EmmaCate8.png', class: 'portfolio-box preset-file3') %>
	                <%= image_tag('emmacate8.gif', class: 'portfolio-box gif-file3') %>
	                <p class="portfolio-text">EmmaCate8.com</p>
	            </a>
	            
	            </div>
	        </div>
	        
	        <div class="col-md-4">
	        	<div class="gifs-rows4">
	        		
	        	<a href="https://www.skylinejourney.com/">
	                 <%= image_tag('SkylineJourney.png', class: 'portfolio-box preset-file4') %>
	                 <%= image_tag('skylinejourney.gif', class: 'portfolio-box gif-file4') %>
	                 <p class="portfolio-text portfolio-padding">SkylineJourney.com</p>
	             </a>
	             
	             </div>
	        </div>
	        
	        <div class="col-md-2"></div>
	        
	        <div class="row">
	        	<div class="col-md-4"></div>
	        	
	        	<div class="col-md-4">
	        		<div class="gifs-rows6">
	        			
	        			<a href="https://www.memeilluminati.com/">
	                 		<%= image_tag('memeilluminati.png', class: 'portfolio-box preset-file6') %>
	                 		<%= image_tag('memeilluminati.gif', class: 'portfolio-box gif-file6') %>
	                 		<p class="portfolio-text portfolio-padding">MemeIlluminati.com</p>
	             		</a>
	             
	             	</div>
	        	</div>
	        	
	        	<div class="col-md-4"></div>
	        </div>
	    </div>
	    
	    <p class="portfolio-logo">Front-end Redesign:</p>
	    <div class="gifs-rows5">
	    	<a href="https://www.tellus360.com/">
	        	<%= image_tag('Tellus360.png', class: 'portfolio-box preset-file5') %>
	        	<%= image_tag('tellus360.gif', class: 'portfolio-box gif-file5') %>
	        	<p class="portfolio-text portfolio-padding">Tellus360.com</p>
	    	</a>
	    </div>
	    
	    <p class="portfolio-logo">Git/Ongoing Projects:</p>
	    <a href="https://bitbucket.org/corourke24/"><p class="portfolio-text portfolio-padding">Bit Bucket</p></a>
	    
	    <a href="/"><h1 class="glitch" data-text="Home">Home</h1></a>
	</div>
</meta>

<script>
	$('img', '.gifs-rows1').hover(function() {
  		$('.preset-file').toggle();
  		$('.gif-file').toggle();
	});
	
	$('img', '.gifs-rows2').hover(function() {
  		$('.preset-file2').toggle();
  		$('.gif-file2').toggle();
	});
	
	$('img', '.gifs-rows3').hover(function() {
  		$('.preset-file3').toggle();
  		$('.gif-file3').toggle();
	});
	
	$('img', '.gifs-rows4').hover(function() {
  		$('.preset-file4').toggle();
  		$('.gif-file4').toggle();
	});
	
	$('img', '.gifs-rows5').hover(function() {
  		$('.preset-file5').toggle();
  		$('.gif-file5').toggle();
	});
	
	
	$('img', '.gifs-rows6').hover(function() {
  		$('.preset-file6').toggle();
  		$('.gif-file6').toggle();
	});
</script>

app/views/static_pages/start.html.erb
	<div class="preloader"><span class="preloader-gif"></span></div>
		
		
   				<div class="center" style="padding-top: 150px;">
					<h1 class="glitch" data-text="How do you feel today?">How do you feel today?</h1>
					<div class="row">
						<div class="hidden">
							<%= link_to image_tag('dark-sun-clear.png'), homelight_url %>
							<%= link_to image_tag('light-sun-clear.png'), homedark_url %>
						</div>
					</div>
					&nbsp;
					<a href="/portfolio"><h1 class="glitch smaller" data-text="Portfolio">Portfolio</h1></a>
		    	</div>
		    	
	</div>